### ISSUE TITLE
В `WallPostType` не хватает варианта `photo`

### ISSUE THREAD

**Issue by vanburgerberg** [vkbottle/types#30]
В документации ВК об этом не написано, но поле `post_type` объекта записи на стене помимо прочего может принимать значение `"photo"`. Как пример вот этот пост: https://vk.com/dev/wall.getById?params[posts]=1_406956. `response[0]["copy_history"][0]["post_type"]` принимает значение `"photo"`

**Comment by FeeeeK** [comment]
fixed in e5c9ebe
